apiVersion: v1
kind: Namespace
metadata:
  name: your-namespace

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quark-app
  namespace: your-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quark-app
  template:
    metadata:
      labels:
        app: quark-app
    spec:
      containers:
        - name: quark-app
          image: your-quark-app-image:tag
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: quark-app-service
  namespace: your-namespace
spec:
  selector:
    app: quark-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: your-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: your-nginx-image:tag
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: your-namespace
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80