version: '3'

services:
  quark-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 8003:80
    depends_on:
      - quark-app