name: Create and publish a Docker image

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        id: login
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate docker-compose-generated.yaml
        run: |
          ./generate.sh
          image_names=$(jq -r '.models[].serviceName' config.json)
          paths=$(jq -r '.models[].modelBasePath' config.json)

      - name: Build the hello-docker Docker image
        run: |
          lowercase_username=$(echo "${{ steps.login.outputs.username }}" | tr '[:upper:]' '[:lower:]')
          for index in "${!image_names[@]}"; do
            image="${image_names[$index]}"
            path="${paths[$index]}"
            
            docker build  "./$path" -t "ghcr.io/$lowercase_username/$image:latest"
            docker push "ghcr.io/$lowercase_username/$image:latest"
          done